$.FM.Const = {
	"FILENAME_DEFAULT": "Untitled",
	"FILETYPE_DEFAULT": "PLAIN",
	"FILETYPE_TEXT": "TEXT",
	"FILESIZE_DEFAULT": 1,
	"FILESIZE_SUFFIX": "Kb",
	"ICON_SORT_DESC": "glyphicon-chevron-down",
	"ICON_SORT_ASC": "glyphicon-chevron-up",
	"ICON_SORT_NAME_ID": "file-name-icon",
	"ICON_SORT_TYPE_ID": "file-type-icon",
	"ICON_SORT_SIZE_ID": "size-icon",
	"NAV_FILE_LIST": "file-list-nav",
	"NAV_BOOKMARKS": "bookmarks-nav",
	"NAV_CLASS_ACTIVE": "active",
	"SUB_HEADER_FILE_LIST": "file-list-sub-header",
	"SUB_HEADER_BOOKMARKS": "bookmarks-sub-header",
	"ACTIONS_GLOBAL": "global-actions",
	"FILE_TABLE_ROW_SELECTED_CLASS": "selected",
	"DATA_INDEX_ATTR_NAME": "data-index",
	"BLOB_HEADERS_TEXT": "text/plain; charset=utf-8",
	"FILE_NAME_PATTERN": "file-name-pattern",
	"MODE_FILE": "file_mode",
	"MODE_BOOKMARK": "bookmark_mode",
	"PILS_ACTIVE_CLASS": "active"
};